apiVersion: v1
kind: Secret
metadata:
    name: {{ .Chart.Name }}-secrets
    namespace: {{ .Values.global.namespace }}
type: Opaque
data:
{{- range $key, $val := .Values.mysql.secret }}
    {{ $key | upper }}: {{ $val | b64enc | quote}}
{{- end }}
