apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: {{ .Values.namespace.todoapp.name }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.todoapp.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.todoapp.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}-secrets-reader
      containers:
      - name: todoapp
        image: {{ .Values.image.todoapp.repository}}: {{.Values.image.todoapp.tag}}
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: app-secrets-volume
          mountPath: "/app/secrets"
          readOnly: true
        - name: app-config-volume
          mountPath: "/app/configs"
          readOnly: true
        resources:
{{ toYaml .Values.todoapp.resources | nindent 12 }}
        env:
        - name: PYTHONUNBUFFERED
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: PYTHONUNBUFFERED
        {{- range $k := .Values.todoapp.secret }}
        - name: {{ $k | upper }}
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name}}-secret
              key: {{ $k | upper }}
        {{- end }}
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: api/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: api/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-data
      - name: app-secrets-volume
        secret:
          secretName: app-secret
      - name: app-config-volume
        configMap:
          name: app-config
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: {{ .Values.todoapp.affinity.nodeAffinity.key }}
                operator: In
                values:
                - {{ .Values.todoapp.affinity.nodeAffinity.values }}
